### ISSUE TITLE
Expecting value: line 1 column 1 (char 0) [x] run.Feed 

### ISSUE THREAD

**Issue by arceuss** [minimaxir/download-tweets-ai-text-gen#25]
C:\Users\arceus\Pictures\arceus but ai>python download_tweets.py arceus413_
Retrieving tweets for @arceus413_...
Oldest Tweet: 2019-12-18 01:41:50:  51%|█████████████████████                    | 13040/25440 [25:11<23:40,  8.73it/s]Expecting value: line 1 column 1 (char 0) [x] run.Feed
[!] if get this error but you know for sure that more tweets exist, please open an issue and we will investigate it!
Expecting value: line 1 column 1 (char 0) [x] run.Feed
[!] if get this error but you know for sure that more tweets exist, please open an issue and we will investigate it!
Expecting value: line 1 column 1 (char 0) [x] run.Feed
[!] if get this error but you know for sure that more tweets exist, please open an issue and we will investigate it!
Expecting value: line 1 column 1 (char 0) [x] run.Feed
[!] if get this error but you know for sure that more tweets exist, please open an issue and we will investigate it!
Oldest Tweet: 2019-12-18 01:41:50:  51%|████████████████████                   | 13060/25440 [25:39<1:41:45,  2.03it/s]Traceback (most recent call last):
  File "download_tweets.py", line 161, in <module>
    fire.Fire(download_tweets)
  File "C:\Users\arceus\AppData\Local\Programs\Python\Python38\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\arceus\AppData\Local\Programs\Python\Python38\lib\site-packages\fire\core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\arceus\AppData\Local\Programs\Python\Python38\lib\site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "download_tweets.py", line 152, in download_tweets
    tweet_data[-1].datetime / 1000.0
IndexError: list index out of range
Oldest Tweet: 2019-12-18 01:41:50:  51%|█████████████████████                    | 13060/25440 [25:39<24:18,  8.49it/s]

**Comment by zephyo** [comment]
Same

**Comment by zephyo** [comment]
Fix found: https://github.com/minimaxir/download-tweets-ai-text-gen/pull/13

**Comment by dudeisbrendan03** [comment]
> Fix found: #13

I don't see how that's a fix if the PR is earlier than the issue
