### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by arceuss** [minimaxir/download-tweets-ai-text-gen#26]
its worked perfectly for me before but now it just outputs
arceus@DESKTOP-5GA669M:/mnt/c/Users/arceus/Pictures/arceus but ai$ python3 download_tweets.py arceus413_
Traceback (most recent call last):
  File "download_tweets.py", line 161, in <module>
    fire.Fire(download_tweets)
  File "/home/arceus/.local/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/arceus/.local/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/arceus/.local/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "download_tweets.py", line 71, in download_tweets
    limit = twint.output.users_list[-1].tweets
IndexError: list index out of range
pretty much any handle does this too

**Comment by luisgbr1el** [comment]
I'm with the same problem.
